### ISSUE TITLE
node-fetch should be a dependency

### ISSUE THREAD

**Issue by seigneur** [ExodusMovement/cryptocompare#1]
npm install does not work, since node-fetch is listed in dev-dependencies. Using Windows :-1:  , so unless I give the dev flag it won't work. Suggest keeping it in dependencies.

**Comment by jprichardson** [comment]
Sorry, I should have documented that you need to bring your `fetch` to the party since some browsers support fetch.

I'd suggest:

```js
global.fetch = require('node-fetch')
```

or

```js
global.fetch = require('isomorphic-fetch')
```

**Comment by jprichardson** [comment]
But why would `npm install` not work?

**Comment by seigneur** [comment]
@jprichardson npm install works, but from cli, it says fetch not found, if I do not do global.fetch = require('node-fetch'). For the browser and maybe even other env it might work.

**Comment by seigneur** [comment]
In btw, downloading exodus now, looks neat. :+1:
