### ISSUE TITLE
Social

### ISSUE THREAD

**Issue by DanielRSnell** [ExodusMovement/cryptocompare#13]
I was wondering if you plan on writing the social queries? 

I have them written out if that would be a helpful contribution? 

Let me know!

**Comment by RyanZim** [comment]
@DanielRSnell I'm not sure I understand?

**Comment by tbutman** [comment]
I believe @DanielRSnell is referring to the data related to social stats that is included in the CryptoCompare API [https://www.cryptocompare.com/api/#-api-data-socialstats-](url)

**Comment by DanielRSnell** [comment]
Yep, that's exactly what i mean! I made a series of new end points for it so that you don't need the IDs, you can query by ticker and name. i'll be releasing in a couple of days!

**Comment by RyanZim** [comment]
This module only covers https://min-api.cryptocompare.com/, not https://www.cryptocompare.com/api/. Closing as out of scope.
