### ISSUE TITLE
How Do I Get Full Historical Data for One Coin?

### ISSUE THREAD

**Issue by pythoncreate** [ExodusMovement/cryptocompare#16]
I'm using the package to load pricing data into my graphs based on a ticker search.  How exactly would i pull historic data all at once for one ticker?

**Comment by joshmu** [comment]
+1

**Comment by RyanZim** [comment]
If you want daily data, use https://github.com/ExodusMovement/cryptocompare#histoday. Use `histoHour` or `histoMinute` for Hour or Minute data.
