### ISSUE TITLE
npm run build fails to minify

### ISSUE THREAD

**Issue by kylewstewart** [ExodusMovement/cryptocompare#19]
Hello, trying to deploy a small app to Heroku include this wonderful library (thank you) and is is failing to minify the code at ./node_modules/cryptocompare/index.js:8 and pointing me toward here  http://bit.ly/2tRViJ9.

**Comment by RyanZim** [comment]
We only support Node versions 6 and higher (and browsers with equivalent support). Sorry.

**Comment by lebed2045** [comment]
the same thing. The module doesn't work on netlify out of a box.
