### ISSUE TITLE
List of FIAT currencies

### ISSUE THREAD

**Issue by kennedybaird** [ExodusMovement/cryptocompare#24]
I can't find anywhere in CryptoCompares documentation about what FIAT currencies they support for price conversions?

If you have any idea that would be great..

**Comment by abhishekgahlot** [comment]
@kennedybaird I added list that is supported by cryptocompare but no docs available this is fetched by recursively iterating over current api and checking which works with cryptocompare api and which not.

https://github.com/ExodusMovement/cryptocompare/pull/28

**Comment by RyanZim** [comment]
Not going to put in a static list, and AFAIK, cryptocompare doesn't have an API for this.
