### ISSUE TITLE
 No option for fiat currency amount to btc value

### ISSUE THREAD

**Issue by Filliposniper** [ExodusMovement/cryptocompare#25]
Before i begin, what am about to say is not a bug or an issue, Am requesting if it could be possible to provide an option where we can parse a fiat currency amount and get the equivalent value in a crypto currency value, I think it would be pretty much helpful to us, a typical example of what am talking about is google crypto converter. "bitcoin to usd" <= making this GET request to google will tell better.

**Comment by jprichardson** [comment]
Please post an example of what how you'd like the existing API of this library to change and what output or result you'd expect. Please be specific.

**Comment by Filliposniper** [comment]
@jprichardson Thanks for the reply, I already found a solution to my problem, but I will still like to share my idea for others.

This is an example of what the API call could have looked like in your plugin.
```
cont cc = require('cryptocompare')
var amount = 100,
      fiatCurrency = 'USD',
      targetCurrency= 'BTC'

cc.customAmount(fiatCurrency,targetCurrency,amount)
.then(prices => {
  console.log(price)
  // Dependent based on the amount given-> { USD: { BTC: 0.015},
})
.catch(console.error)
```
My own solution to the custom amount

```
//make an API request to cryptocompare price API url

let request = require('request')

var amount = 100,
var answer

request({url: `https://min-api.cryptocompare.com/data/price?fsym=BTC&tsyms=USD`}, function(err,result,body){
        if(result.headers["content-type"] !== "application/json"){
            var data = JSON.parse(body);
            let BTC_amount = amount / data.USD;
            // normally it gives a long float number, so you can round it up if you wish
            let final = (BTC_amount.toFixed(6))
           // Parse the rounded up value outside request function
            answer = final
           console.log(answer) // logs_out 0.015 dependent on the current value
        } else {
            console.log(err)
        }
    })

```

**Comment by RyanZim** [comment]
This is a lightweight wrapper on the cryptocompare API; I'm not interested in adding second-layer logic.
