### ISSUE TITLE
Question: How to query via ES6 / React JS

### ISSUE THREAD

**Issue by interpegasus** [ExodusMovement/cryptocompare#29]
Hi, First of all, thank you for sharing this library.

I would like to know how to import it and use it in a React JS / ES6 project?

So far I have tried via:
```
import {CryptoCompare} from 'cryptocompare';
CryptoCompare.coinList();  // It returns undefined
```
Thank you!

**Comment by RyanZim** [comment]
import CryptoCompare from 'cryptocompare';
