### ISSUE TITLE
es6 -> commonjs

### ISSUE THREAD

**Issue by CraigglesO** [ExodusMovement/cryptocompare#3]
Would you be willing to simplify the code for npm install (production)

Uglify.js does not like your code for obvious reasons.

**Comment by jprichardson** [comment]
I don't understand... this module is using commonjs....

**Comment by jprichardson** [comment]
Have a look... https://github.com/ExodusMovement/cryptocompare/blob/0.1.0/index.js

**Comment by jprichardson** [comment]
Ah, I'm guessing you're referring to the usage of the enhanced object literals on the exports... this module exists to serve Exodus and if I commit to this small portion, that means I'll tie it to ES5. I can't do that when it's so easy to babelify these things. But it does work just fine in newer Node/commonjs versions (I forgot which version started supporting the new object literal syntax.. v5?) without Babel.

**Comment by CraigglesO** [comment]
I mean to write `es5 commonjs`

es6 modules don't work well with webpack/uglify config because as of yet, uglify still can not process new es6 like `() =>` and `${var}` strings

**Comment by jprichardson** [comment]
If you're delivering for Node.js/Electron, you don't need to uglify a 3rd party module. If you're delivering to the browser, you need to browserify/webpack anyways since it has `module.exports`.

**Comment by CraigglesO** [comment]
Yes, I am delivering to a browser. My point is, your code does not work with uglify. I am sure I could switch to babili and I wouldn't have issues. But when it bundles everything into one minified js file for production, it errors, because uglify.js does not recognize the code.

Does that make sense?

**Comment by CraigglesO** [comment]
The easiest way I can think of to simplify the code though (install babel first):
`babel index.js > out.js`

This makes the file usable for everything.

**Comment by jprichardson** [comment]
If you're delivering to the browser, you're using Webpack or Browserify, right? If so, drop in a Bablel plugin in the pipeline before you Uglify and the problem is solved.
