### ISSUE TITLE
How to handle SBD* (Steem Dollars) and SCR* (Scorum)

### ISSUE THREAD

**Issue by sxiii** [ExodusMovement/cryptocompare#39]
Greetings.

I'm trying to do the following:

```
cc.priceMulti(['STEEM', 'SBD*', 'GOLOS', 'GBG', 'SCR*', 'VIT'], ['USD', 'BTC']).then(prices => {
	console.log(prices.SBD*.USD);
        console.log(prices.SCR*.USD);
} ).catch(console.error)
```
But because the SBD contains the star symbol javascript drops out with error:
`SyntaxError: Unexpected token .`

When I'm trying to add quotes like ' and ", or use backslash to protect the star like SBD\*, it doesen't help either.

When I am trying to navigate inside the array like prices[0][1].USD; javascript drops out with error `SyntaxError: missing ) after argument list`. 

Is there any ways of using data about SBD and SCR cryptos?

Thanks.

Den

**Comment by RyanZim** [comment]
You need to do `console.log(prices['SBD*'].USD)`

**Comment by sxiii** [comment]
> You need to do `console.log(prices['SBD*'].USD)`

Wow thank you very much for your fast & easy solution. Should have found this myself :)
