### ISSUE TITLE
What does the default exchange value CCCAGG mean?

### ISSUE THREAD

**Issue by nlhuykhang** [ExodusMovement/cryptocompare#4]
Do you know what the value CCCAGG means?

Thank you for the module too

**Comment by RyanZim** [comment]
I'm not positive what it stands for, but I think it's cryptocompare's aggregated data.

**Comment by jprichardson** [comment]
ping @vcealicu 😄

**Comment by MMquant** [comment]
CCCAGG = CryptoCompare Current AGGregate. [Calculation] (https://www.cryptocompare.com/coins/guides/how-does-our-cryptocurrecy-index-work/)

**Comment by MMquant** [comment]
CCCAGG = CryptoCompare Current Aggregate.
[Calculation](https://www.cryptocompare.com/coins/guides/how-does-our-cryptocurrecy-index-work/)

**Comment by RyanZim** [comment]
Thanks @MMquant!

**Comment by CookieFevereiro** [comment]
"The Crypto Coin Comparison Aggregated Index (“CCCAGG”) refers to the real-time index calculation methodology, the purpose of which is to show the best price estimation for crypto traders and
investors to value their portfolio at any time. It aggregates transaction data of over 70 exchanges,
using 24 hour volume weighted average. The CCCAGG is calculated for each crypto coin in each
currency it is trading in (example: CCCAGG BTC-USD)."

https://www.cryptocompare.com/media/12318004/cccagg.pdf
