### ISSUE TITLE
2 functions are missing

### ISSUE THREAD

**Issue by slidenerd** [ExodusMovement/cryptocompare#5]
**CoinSnapshot**

Get data for a currency pair. It returns general block explorer information, aggregated data and individual data for each exchange available

**CoinSnapshotFullById**
Get the general, subs (used to connect to the streamer and to figure out what exchanges we have data for and what are the exact coin pairs of the coin) and the aggregated prices for all pairs available.

Thanks for adding them in advance

**Comment by RyanZim** [comment]
This module uses https://min-api.cryptocompare.com/; not https://www.cryptocompare.com/api/. min-api does not have those api calls.
