### ISSUE TITLE
Example of data parsed to csv

### ISSUE THREAD

**Issue by markcots** [ExodusMovement/cryptocompare#8]
Thank you for sharing your code. Works great and looks clean, tidy, optimal. Very nice work, well done.

Would it be possible to show an example of return data being outputted to csv file instead of console.log ?
e.g. working from ...
cc.histoDay('BTC', 'USD', { limit: 'none' } ).then(data => { "output data to csv file" })

Standard csv format ...
Row 1 field headers ...
time, close, high, low, open, volumefrom, volumeto
Row 2 onwards ...
1485388800, 915.65, 917.71, 893.81, 893.97, 35494.93, 32333344.2
and so on

Hope that's clear, thank you for your consideration, Mark

**Comment by jprichardson** [comment]
@markcots sorry Mark. This is outside the scope of what we're willing to provide. I'd suggest taking a look at the number of CSV modules on npm: https://www.npmjs.com/search?q=csv and perhaps ask the question on stackoverflow.com
